# Use Python 3.10.9 as the base image
FROM python:3.10.9

# Set the working directory in the container to /app
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application's code
COPY src/ src/

# Command to run when starting the container
CMD ["python", "src/main.py"]
